apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
        - name: backend
          image: parasb402/backend3
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/techdome_db"
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
        - name: frontend
          image: parasb402/frontend
          ports:
            - containerPort: 3000
