version: "3.8"

services:
  backend:
    container_name: "backend_container"
    image: parasb402/backend3
    restart: always
    environment:
      - PORT=8084
      - MONGODB_URI=mongodb://mongo_db:27017/techdome_db
    depends_on:
      - mongo_db

  mongo_db:
    container_name: "database_container"
    image: mongo:latest

  frontend:
    container_name: "frontend_container"
    image: parasb402/frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
