apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: multi-container
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: multi-container
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: multi-container
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
